 create table User(
      user_id bigint generated by default as identity(start with 1) primary key, 
  	  user_name varchar_ignorecase(50) not null,
      user_login varchar_ignorecase(50) not null,
      user_password varchar_ignorecase(50) not null
  );

  create table Permission_Group(
  	  group_id bigint generated by default as identity(start with 1) primary key, 
      group_name varchar_ignorecase(50) not null
  );
  
  create table User_Group(
  	  user_group_id bigint generated by default as identity(start with 1) primary key, 
      user_id bigint not null, 
      group_id bigint not null, 
  	  constraint fk_user_group foreign key(group_id) references Permission_Group(group_id),
  	  constraint fk_user_group_user foreign key(user_id) references User(user_id)
  );
  
  create table Permission(
      permission_id bigint generated by default as identity(start with 1) primary key, 
      permission varchar_ignorecase(50) not null
  );
  
  
  create table Group_Permission(
      group_id bigint not null, 
      permission_id bigint not null, 
      constraint fk_group_permission foreign key(permission_id) references Permission(permission_id),
      constraint fk_group_permission_group foreign key(group_id) references Permission_Group(group_id)
  );
  
     



